# Generated by Django 5.2.15 on 2026-06-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadjob',
            name='reference_range',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
