# Generated by Django 5.2.15 on 2026-06-17 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_uploadjob_reference_range'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('supplier', 'Supplier'), ('salary', 'Salary'), ('remittancePRN', 'Remittance PRN'), ('remittanceTR', 'Remittance TR'), ('foreign', 'Foreign')], help_text='The payment type this template is for', max_length=30, unique=True)),
                ('template_file', models.FileField(help_text='Excel template file (.xlsx or .xls)', upload_to='templates/%Y/%m/')),
                ('version', models.CharField(default='1.0', help_text='Template version number', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Optional description of this template')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this template is available for download')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Template',
                'verbose_name_plural': 'Payment Templates',
                'ordering': ['payment_type'],
            },
        ),
    ]
